# Generated by Django 4.2.7 on 2023-11-29 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='password',
            new_name='user_pass',
        ),
    ]
