# Generated by Django 4.2.7 on 2023-11-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0003_testingtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoreTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.IntegerField()),
                ('length', models.IntegerField()),
                ('Shape', models.CharField(max_length=100)),
            ],
        ),
    ]
